# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/salar/dlib_ws

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/salar/dlib_ws/build

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/salar/dlib_ws/build/CMakeFiles /home/salar/dlib_ws/build/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/salar/dlib_ws/build/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named u-net

# Build rule for target.
u-net: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 u-net
.PHONY : u-net

# fast build rule for target.
u-net/fast:
	$(MAKE) -f CMakeFiles/u-net.dir/build.make CMakeFiles/u-net.dir/build
.PHONY : u-net/fast

#=============================================================================
# Target rules for targets named u-net3

# Build rule for target.
u-net3: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 u-net3
.PHONY : u-net3

# fast build rule for target.
u-net3/fast:
	$(MAKE) -f CMakeFiles/u-net3.dir/build.make CMakeFiles/u-net3.dir/build
.PHONY : u-net3/fast

#=============================================================================
# Target rules for targets named u-net2

# Build rule for target.
u-net2: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 u-net2
.PHONY : u-net2

# fast build rule for target.
u-net2/fast:
	$(MAKE) -f CMakeFiles/u-net2.dir/build.make CMakeFiles/u-net2.dir/build
.PHONY : u-net2/fast

#=============================================================================
# Target rules for targets named dlib

# Build rule for target.
dlib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 dlib
.PHONY : dlib

# fast build rule for target.
dlib/fast:
	$(MAKE) -f dlib_build/CMakeFiles/dlib.dir/build.make dlib_build/CMakeFiles/dlib.dir/build
.PHONY : dlib/fast

u-net.o: u-net.cpp.o

.PHONY : u-net.o

# target to build an object file
u-net.cpp.o:
	$(MAKE) -f CMakeFiles/u-net.dir/build.make CMakeFiles/u-net.dir/u-net.cpp.o
.PHONY : u-net.cpp.o

u-net.i: u-net.cpp.i

.PHONY : u-net.i

# target to preprocess a source file
u-net.cpp.i:
	$(MAKE) -f CMakeFiles/u-net.dir/build.make CMakeFiles/u-net.dir/u-net.cpp.i
.PHONY : u-net.cpp.i

u-net.s: u-net.cpp.s

.PHONY : u-net.s

# target to generate assembly for a file
u-net.cpp.s:
	$(MAKE) -f CMakeFiles/u-net.dir/build.make CMakeFiles/u-net.dir/u-net.cpp.s
.PHONY : u-net.cpp.s

u-net2.o: u-net2.cpp.o

.PHONY : u-net2.o

# target to build an object file
u-net2.cpp.o:
	$(MAKE) -f CMakeFiles/u-net2.dir/build.make CMakeFiles/u-net2.dir/u-net2.cpp.o
.PHONY : u-net2.cpp.o

u-net2.i: u-net2.cpp.i

.PHONY : u-net2.i

# target to preprocess a source file
u-net2.cpp.i:
	$(MAKE) -f CMakeFiles/u-net2.dir/build.make CMakeFiles/u-net2.dir/u-net2.cpp.i
.PHONY : u-net2.cpp.i

u-net2.s: u-net2.cpp.s

.PHONY : u-net2.s

# target to generate assembly for a file
u-net2.cpp.s:
	$(MAKE) -f CMakeFiles/u-net2.dir/build.make CMakeFiles/u-net2.dir/u-net2.cpp.s
.PHONY : u-net2.cpp.s

u-net3.o: u-net3.cpp.o

.PHONY : u-net3.o

# target to build an object file
u-net3.cpp.o:
	$(MAKE) -f CMakeFiles/u-net3.dir/build.make CMakeFiles/u-net3.dir/u-net3.cpp.o
.PHONY : u-net3.cpp.o

u-net3.i: u-net3.cpp.i

.PHONY : u-net3.i

# target to preprocess a source file
u-net3.cpp.i:
	$(MAKE) -f CMakeFiles/u-net3.dir/build.make CMakeFiles/u-net3.dir/u-net3.cpp.i
.PHONY : u-net3.cpp.i

u-net3.s: u-net3.cpp.s

.PHONY : u-net3.s

# target to generate assembly for a file
u-net3.cpp.s:
	$(MAKE) -f CMakeFiles/u-net3.dir/build.make CMakeFiles/u-net3.dir/u-net3.cpp.s
.PHONY : u-net3.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... u-net"
	@echo "... u-net3"
	@echo "... edit_cache"
	@echo "... u-net2"
	@echo "... rebuild_cache"
	@echo "... dlib"
	@echo "... u-net.o"
	@echo "... u-net.i"
	@echo "... u-net.s"
	@echo "... u-net2.o"
	@echo "... u-net2.i"
	@echo "... u-net2.s"
	@echo "... u-net3.o"
	@echo "... u-net3.i"
	@echo "... u-net3.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

